name: Code verification with Ruff and PyTest

on: [push]
  
jobs:
  code_verification:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Ruff verification
      run: ruff check .
    - name: Run PyTest
      run: pytest
        

# TODO: Add automatic push to PyPi when branching model is established